# Exercícios NumPy - Estrutura Unidimensional

In [7]:
pip install numpy


Note: you may need to restart the kernel to use updated packages.



[notice] A new release of pip is available: 23.1.2 -> 24.0
[notice] To update, run: python.exe -m pip install --upgrade pip


In [8]:
pip install pandas

                                              0.0/11.6 MB ? eta -:--:--
                                              0.2/11.6 MB 4.8 MB/s eta 0:00:03
     -                                        0.4/11.6 MB 3.7 MB/s eta 0:00:04
     -                                        0.5/11.6 MB 3.6 MB/s eta 0:00:04
     -                                        0.5/11.6 MB 2.7 MB/s eta 0:00:05
     -                                        0.5/11.6 MB 2.6 MB/s eta 0:00:05
     -                                        0.5/11.6 MB 2.6 MB/s eta 0:00:05
     -                                        0.5/11.6 MB 2.6 MB/s eta 0:00:05
     -                                        0.5/11.6 MB 2.6 MB/s eta 0:00:05
     -                                        0.5/11.6 MB 2.6 MB/s eta 0:00:05
     --                                       0.6/11.6 MB 1.3 MB/s eta 0:00:09
     --                                       0.7/11.6 MB 1.3 MB/s eta 0:00:09
     --                                       0.7/11.6 MB 1


[notice] A new release of pip is available: 23.1.2 -> 24.0
[notice] To update, run: python.exe -m pip install --upgrade pip


In [42]:
import numpy as np 
import pandas as pd



In [16]:
# 1. Exercicio de Criação

array = np.array([1,2,3,4,5,6,7,8,9,10])
array

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [11]:
lista = [1,2,3,4,5,6,7,8,9,10]

tupla = (1,2,3,4,5,6,7,8,9,10)

df_series = pd.Series(tupla)

In [13]:
df_series


0     1
1     2
2     3
3     4
4     5
5     6
6     7
7     8
8     9
9    10
dtype: int64

In [15]:
df_series.info()

<class 'pandas.core.series.Series'>
RangeIndex: 10 entries, 0 to 9
Series name: None
Non-Null Count  Dtype
--------------  -----
10 non-null     int64
dtypes: int64(1)
memory usage: 212.0 bytes


In [39]:
# 3. Exercicio de Acesso 
array1to10 = np.array([1,2,3,4,5,6,7,8,9,10])
quarto_elemento = array1to10[3]
print("O quarto elemento do array é:", quarto_elemento)

O quarto elemento do array é: 4


In [20]:
# 3. Exercicio de Soma

array1to5 = np.array([1, 2, 3, 4, 5])
array6to10 = np.array([6, 7, 8, 9, 10])
soma_arrays = array1to5 + array6to10
print("A soma dos arrays é:", soma_arrays)



A soma dos arrays é: [ 7  9 11 13 15]


In [37]:
# 4. Exercicio de Filtragem
array1to10 = np.array([1,2,3,4,5,6,7,8,9,10])
array_maiores_que_5 = array1to10[array1to10>5]
print("Valores maiores que 5:", array_maiores_que_5)

Valores maiores que 5: [ 6  7  8  9 10]


In [27]:
# 5. Exercício de Estatísticas:

print("Média:", array.mean())
print("Desvio padrão:", array.std())

Média: 5.5
Desvio padrão: 2.8722813232690143


In [26]:
# 6. Exercício de Concatenação:

arr_concat = np.concatenate([arr1, arr2])
print("Concatenação:")
print(arr_concat)


Concatenação:
[ 1  2  3  4  5  6  7  8  9 10 10  9  8  7  6  5  4  3  2  1]


In [25]:
# 7. Exercício de Subtração:

arr1 = np.arange(1, 11)
arr2 = np.arange(10, 0, -1)
resultado = arr1 - arr2
print("Resultado da Subtração:", resultado)

Resultado da Subtração: [-9 -7 -5 -3 -1  1  3  5  7  9]


In [29]:
# Exercício de Ordenação:

arr1 = np.arange(1, 11)
arr_ordenado = np.sort(arr1)[::-1]
print(arr_ordenado)

[10  9  8  7  6  5  4  3  2  1]


In [30]:
# Exercício de Verificação de Valores Únicos:

arr = np.array([0, 4, 2, 6, 5, 9, 6])
print("Valores Duplicados:", np.unique(arr).size != arr.size)

Valores Duplicados: True


In [40]:
# Exercício de Slicing:

print("Slicing do terceiro ao sétimo elemento:")
print(arr[2:7])

Slicing do terceiro ao sétimo elemento:
[2 6 5 9 6]


# Aula 04

In [ ]:
# arr = np.array([0, 4, 5 ,6, 9, 6])

# valores_duplicados = 

In [47]:
# data = {'Name':['Tom', 'nick', 'krish', 'jack'],
#         'Age':[20, 21, 19, 18]}

# df = pd.DataFrame(data)

# df

Name  Age
0    Tom   20
1   nick   21
2  krish   19
3   jack   18

In [49]:
# notas_alunos = {
#     'João': {"matemática": 90, "português": 85, "ciências": 88},
#     'Maria': {"matemática": 95, "português": 92, "ciências": 89},
#     'Pedro': {"matemática": 80, "português": 75, "ciências": 82}
# }

In [50]:
# notas_alunos["Ana"] = {"matemática": 88, "português": 91, "ciências": 85}

In [ ]:
# Criando dicionários em Python

# Exemplo 07

# df.to_cvs('exemplo.css')
# df.to_excel('exemplo.xlsx')

In [ ]:
# df.to_excel('exemplo.xlsx')

In [107]:
# Criar um dicionário
data = {
    'Produto': ["celular", "celular", "celular", "tablet",  "tablet",  "tablet", "notebook",  "notebook",  "notebook"],
    'Mês': ['01-01-2023', '01-02-2023', '01-03-2023', '01-01-2023', '01-02-2023', '01-03-2023', '01-01-2023', '01-02-2023', '01-03-2023'],
    'Vendas': [150, 180, 200, 100, 120, 130, 80, 90, 100]
}
data 

df = pd.DataFrame(data)
df

Produto         Mês  Vendas
0   celular  01-01-2023     150
1   celular  01-02-2023     180
2   celular  01-03-2023     200
3    tablet  01-01-2023     100
4    tablet  01-02-2023     120
5    tablet  01-03-2023     130
6  notebook  01-01-2023      80
7  notebook  01-02-2023      90
8  notebook  01-03-2023     100

In [108]:
df['Mês'] = pd.to_datetime(df['Mês'], format = '%d-%m-%Y')
df['Ano'] = df['Mês'].dt.year
df['Mês'] = df['Mês'].dt.month

# Converter DataFrane para um Panda Series indicado pelos meses
vendas_series= pd.Series(df['Vendas'].values, index=df['Mês'])

# Identificar o produto mais vendido e menos vendido
produto_mais_vendido = df.groupby('Produto')['Vendas'].sum().idxmax()
produto_menos_vendido = df.groupby('Produto')['Vendas'].sum().idxmin()
produto_mais_vendido
produto_menos_vendido


'notebook'

In [111]:
# Calcular a media, mediana, máxima e mínimo de vendas mensais

media_vendas = vendas_series.mean()
media_vendas


127.77777777777777

In [114]:

mediana_vendas = vendas_series.median()
mediana_vendas

120.0

In [116]:
maxima_vendas = vendas_series.max()
maxima_vendas

200

In [117]:
minimo_vendas = vendas_series.min()
minimo_vendas

80